M48
; DRILL file {KiCad 9.0.4} date 2025-09-26T18:44:51-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-26T18:44:51-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X91.694Y-89.356
T2
X129.54Y-44.45
M30
